x=int(input("Number 1 :"))
y=int(input("Number 2 :"))

print(f"{x} + {y}")
print(x+y)
print("------------------")
print(f"{x} - {y}")
print(x-y)
print("------------------")
print(f"{x} * {y}")
print(x*y)
print("------------------")
print(f"{x} / {y}")
print(x/y)